/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShalmaIcon {
        "iconName": string;
    }
}
declare global {
    interface HTMLShalmaIconElement extends Components.ShalmaIcon, HTMLStencilElement {
    }
    var HTMLShalmaIconElement: {
        prototype: HTMLShalmaIconElement;
        new (): HTMLShalmaIconElement;
    };
    interface HTMLElementTagNameMap {
        "shalma-icon": HTMLShalmaIconElement;
    }
}
declare namespace LocalJSX {
    interface ShalmaIcon {
        "iconName": string;
    }
    interface IntrinsicElements {
        "shalma-icon": ShalmaIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shalma-icon": LocalJSX.ShalmaIcon & JSXBase.HTMLAttributes<HTMLShalmaIconElement>;
        }
    }
}
