/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpotIcon {
        "iconName": string;
    }
}
declare global {
    interface HTMLSpotIconElement extends Components.SpotIcon, HTMLStencilElement {
    }
    var HTMLSpotIconElement: {
        prototype: HTMLSpotIconElement;
        new (): HTMLSpotIconElement;
    };
    interface HTMLElementTagNameMap {
        "spot-icon": HTMLSpotIconElement;
    }
}
declare namespace LocalJSX {
    interface SpotIcon {
        "iconName": string;
    }
    interface IntrinsicElements {
        "spot-icon": SpotIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "spot-icon": LocalJSX.SpotIcon & JSXBase.HTMLAttributes<HTMLSpotIconElement>;
        }
    }
}
